// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1sKUheSJtBRWH8DyHT0MSQ7JjgZJGM3E',
    appId: '1:506833480853:web:0d729f5dd602eee5c43f9c',
    messagingSenderId: '506833480853',
    projectId: 'fluttersample-b90c5',
    authDomain: 'fluttersample-b90c5.firebaseapp.com',
    storageBucket: 'fluttersample-b90c5.appspot.com',
    measurementId: 'G-2V43277XRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4VQHGXXtGlTNrGLAQx_r2u67HC7iOeXI',
    appId: '1:506833480853:android:c85795a73365b47cc43f9c',
    messagingSenderId: '506833480853',
    projectId: 'fluttersample-b90c5',
    storageBucket: 'fluttersample-b90c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-e75tPeXtGkQzyX5we9dH-2Eg2FSUA4E',
    appId: '1:506833480853:ios:09f6da75e107ef41c43f9c',
    messagingSenderId: '506833480853',
    projectId: 'fluttersample-b90c5',
    storageBucket: 'fluttersample-b90c5.appspot.com',
    iosClientId: '506833480853-4auo4luudimt2dt6j6341fa6iln5cv58.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
